### ISSUE TITLE
Full traceback

### ISSUE THREAD

**Issue by armintoepfer** [mgawan/GPU-BSW#15]
Hi!

Would it be possible to add the full traceback? For a generic alignment implementation, this is of utmost importance to me.

Thanks,
Armin

**Comment by mgawan** [comment]
Hi, thanks for checking. A full traceback implementation is almost complete, its just low on priority for our bioinformatics group hence the delay but I will try to push a code for that soon. It's on my to do list for next month.

**Comment by mgawan** [comment]
One of our interns has been hard at work on the traceback implementation. She will soon be making a pull request [here at the new home of ADEPT](https://github.com/mgawan/ADEPT).
