### ISSUE TITLE
Error when executing with a protein database

### ISSUE THREAD

**Issue by ManuelCostanzo** [mgawan/GPU-BSW#18]
Hi, I hope you are doing well,

I have a problem when executing with a protein database ([uniprot_sprot](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/)). I run with this command:

`./program_gpu aa uniprot_sprot.fasta query.fasta ./out`

But always I have this error:

`terminate called after throwing an instance of 'std::logic_error' 
  what():  basic_string::_M_construct null not valid`

Do you know what is happening? I have a GeForce RTX 2070, but I don't think that is why. If I run with the test data, everything works perfectly.

Thanks in advance!

**Comment by mgawan** [comment]
Hi,
the uniprot_sprot.fasta uses a slightly different file format than the test dataset. Test datasets have one sequence in one line while the above database breakdown each sequence into smaller sub-sequences and places each subsequence on a new line. You may need to modify the file reading portion of the code in main.cpp file to suite your input data. Or may be just use any other fasta file reader, just make sure that first two arguments of driver::kernel_driver_aa() are vectors of strings that contain reference and query sequences. I am a little occupied right now but if you want I can help you write/find a file reader for your data in next week. 

Thanks

**Comment by ManuelCostanzo** [comment]
Hi,

Thank you for your response. I will try to modify the code and I will tell you. Another question I have is: what does the result mean? Because with the test data, I get only a matrix, but I don't know anything about the scores or sequences like [SWhybrid](https://github.com/turbo0628/SWhybrid). Can I somehow get a result like that? For example:

score 497 -- >gi|816799270|gb|KKN75037.1| hypothetical protein LCGC14_0384110, partial [marine sediment metagenome]
score 373 -- >gi|816760533|gb|KKN41062.1| hypothetical protein LCGC14_0727120 [marine sediment metagenome]
score 357 -- >gi|143302314|gb|EDE20598.1| hypothetical protein GOS_1171242, partial [marine metagenome]
score 353 -- >gi|816543413|gb|KKL55155.1| hypothetical protein LCGC14_2258220, partial [marine sediment metagenome]
score 331 -- >gi|143177023|gb|EDD37053.1| hypothetical protein GOS_1315847, partial [marine metagenome]
score 330 -- >gi|135253791|gb|EBG44713.1| hypothetical protein GOS_9431765, partial [marine metagenome]
score 322 -- >gi|143880528|gb|EDH29922.1| hypothetical protein GOS_630718, partial [marine metagenome]
score 314 -- >gi|143324238|gb|EDE33522.1| hypothetical protein GOS_1148440, partial [marine metagenome]
score 308 -- >gi|136135495|gb|EBM14790.1| hypothetical protein GOS_8455521, partial [marine metagenome]
score 307 -- >gi|143406335|gb|EDE78403.1| hypothetical protein GOS_1070628, partial [marine metagenome]

Thanks

**Comment by mgawan** [comment]
I see that you are trying to use it for performing a database search, while in its current state it is intended to be a library that you can integrate in your workflow. This program is just an example of how you would use it. Currently each row of output file contains the following:

`alignment score, reference sequence start location, reference sequence end location, query sequence begin location, query sequence end location. `

If you can explain your use case to me, I might be able to help you integrate this in your code/software pipeline.

**Comment by mgawan** [comment]
I am going to close this issue because of lack of response, feel free to reopen again. I would also suggest to try out the release of ADEPT: https://github.com/mgawan/ADEPT
